graph TB
    User ||--o{ Post : hasMany
    User }o--o{ Role : belongsToMany
    User ||--|| UserProfile : hasOne
    Post }o--|| User : belongsTo
    Post ||--o{ Comment : hasMany
    Post }o--o{ Tag : belongsToMany
    Post }o--|| Category : belongsTo
    Comment }o--|| Post : belongsTo
    Comment }o--|| User : belongsTo
    Comment ||--o{ Comment : hasMany
    Category ||--o{ Post : hasMany
    Category ||--o{ Category : hasMany
    Tag }o--o{ Post : belongsToMany
    Role }o--o{ User : belongsToMany
    UserProfile }o--|| User : belongsTo